language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:tehnick/leechcraft-stable
  - sudo add-apt-repository -y ppa:kostko/boost
  - sudo add-apt-repository -y ppa:george-edison55/gcc4.7-precise
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.7 cmake libboost-thread1.53-dev libboost-date-time1.53-dev libboost-filesystem1.53-dev libboost-regex1.53-dev libboost-program-options1.53-dev libqt4-dev libqxmpp-dev libqtwebkit-dev libgeoip-dev libtelepathy-qt4-dev libqscintilla2-dev libpoppler-qt4-dev libpoppler-cpp-dev libdjvulibre-dev libhunspell-dev libspectre-dev liblastfm-dev libqjson-dev libmagic-dev libpcre3-dev libqca2-dev libotr2-dev libaspell-dev libspeex-dev libtag1-dev libqwt-dev libqxt-dev libmsn-dev libbz2-dev zlib1g-dev libx11-dev x11proto-randr-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libguess-dev
  - sudo apt-get download libtorrent-rasterbar-dev libtorrent-rasterbar6
  - sudo dpkg --force-depends -i libtorrent-*
script: mkdir build && cd build && cmake ../src -DENABLE_SYNCER=False -DENABLE_OTLOZHU=False && make
